# Generated by Django 2.1.7 on 2019-03-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('sigla', models.CharField(max_length=255, verbose_name='Sigla')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('descricao', models.TextField(verbose_name='Sigla')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('periodo', models.CharField(max_length=1, verbose_name='Período')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='edital',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Programa'),
        ),
        migrations.AddField(
            model_name='edital',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Tipo'),
        ),
    ]
